### ISSUE TITLE
RTSP CPU, Memory usage

### ISSUE THREAD

**Issue by DongkyuK25** [emgucv/emgucv#889] opened 2023-11-09 01:40 UTC
I want know why my cpu usage and memory usage is being high. 
if my cam frame size is (3840x2160), it can cause high cpu, memory?
i used capture.set(capprops.FrameWidth, 1280) , capture.set(capprops,FrameHeight, 780) 
but it doesn't active. 
i just make new capture instance with my url. 
capture.start() only.  not even capture.retrieve();
no event or convert to image<bgr,byte>.
i want know how to reduce my cpu usage. 
it become higher almost 50%. please tell me how to resolve it. 
Thank you

**Comment by emgucv** [comment] 2023-11-09 14:13
Looks like a duplicate of issue #888 . Please keep track of the issue using the same ticket. Closing this for now.

**Closed by emgucv** 2023-11-09 14:13 UTC
