### ISSUE TITLE
Emgucv 4.5.4.4788 can't install on .net framewok 4.8?

### ISSUE THREAD

**Issue by One-One-Code** [emgucv/emgucv#631] opened 2021-10-30 12:16 UTC
I have installed  Emgucv 4.5.4.4788
however, run application throw exception  Unable to load DLL 'cvextern' 

so I install  Emgu.CV.runtime.windows   4.5.4.4788, but I can't install it success

how to solve it ?

**Comment by One-One-Code** [comment] 2021-10-30 12:17
![image](https://user-images.githubusercontent.com/44698989/139532558-f321c23f-7936-40de-aba5-14ed9ce6a1f1.png)

**Comment by emgucv** [comment] 2021-11-01 13:09
Duplicate of #399 #600 #614

See instructions here:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Upgrade_from_packages.config_to_package_reference

If you are targeting .net framework 4.8, please also read this:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Targeting_.Net_Framework

**Comment by emgucv** [comment] 2021-11-25 19:28
Closing ticket now.

**Closed by emgucv** 2021-11-25 19:28 UTC
