### ISSUE TITLE
EigenFaceRecogniser fails to produce error on detecting new face

### ISSUE THREAD

**Issue by Maitreya-Bhatkhande** [emgucv/emgucv#597] opened 2021-10-05 05:49 UTC
Whenever a new face is detected, `.Predict()` method always returns `predictionResult.Label = 0` and `predictionResult.Distance = 0` and recognizes that face as same as the most latest correctly recognized face.

**My Platform:-**
      Windows

**.Net version used:-**
     .NetFramework 4.7.2

**Mys system's CPU Architecture:-**
      x64 

**Emgu CV package used:-**
     Through Nuget Package manager -- EmguCV -- version 3.1.0.1

**To Reproduce:-**
```
       Image<Gray, byte> image = resultImage.Convert<Gray, byte>().Resize(100, 100, (Inter)2);
       CvInvoke.EqualizeHist((IInputArray)image, (IOutputArray)image);
       FaceRecognizer.PredictionResult predictionResult = ((FaceRecognizer)this.eigenFaceRecognizer).Predict((IInputArray)image);
       
       //"resultImage" here, is the frame grabbed from webcam
```

**Expected behavior:-**
      When new face is detected, `predictionResult.Label != -1 && predictionResult.Distance < 1E+19` -- This condition should not   
      be satisfied .

**Comment by emgucv** [comment] 2021-10-21 18:31
EigenFaceRecognizer.Predict will return the nearest Face. 

If you want to reject Faces that are significantly different from those been trained, you should check the value of "predictionResult.Distance". If the distance is bigger than a threshold, reject it as a match. 

This thresold value varies depends on your parameters.

**Comment by Maitreya-Bhatkhande** [comment] 2021-12-20 04:15
That is what the problem is. The `predictionResult.Label` and `predictionResult.Distance` always return **0**, irrespective of the face is trained or not.

**Comment by emgucv** [comment] 2022-02-28 16:18
Our unit test here:

https://github.com/emgucv/emgucv/blob/4.5.5/Emgu.CV.Test/AutoTestVarious.cs#L1456

returns the correct labels and distances. 

We are not able to reproduce your issue.

**Comment by emgucv** [comment] 2022-04-07 13:49
Closing ticket now.

**Closed by emgucv** 2022-04-07 13:49 UTC
