### ISSUE TITLE
Image<,> won't dispose!

### ISSUE THREAD

**Issue by Ahmad-Agbaria** [emgucv/emgucv#195] opened 2018-12-22 22:58 UTC
**This bug was reported by a lot but none answered!** I am disposing all created objects but my app is still using more and more memory till it crashes. I nearly tried everything, including: .Dispose() =null using() and even GC was running nearly every half a second, nothing did work! Here's my code (I am sending about 100 images to the following function):

```
    private void ProcessImage (Image<Bgr, byte> imgInput)
    {
        imgInput._SmoothGaussian(5);            
    }
```
Also I tried to update the code to the following, but my program freezes and crashes!

```
        IntPtr image = imgInput;
        imgInput._SmoothGaussian(5);
        CvInvoke.cvReleaseImage(ref image);
```

**_Important Update:_ if the function finishes before my program crashes, surprisingly it will release All of the memory. I have added a graph.**

Uploaded image could be found here: https://i.ibb.co/nBGTHVZ/Example.jpg

I am using VS 2017, Win10 64-bit, both up to date, and last stable version of EmguCV 3.4.X.

**Comment by emgucv** [comment] 2018-12-31 21:33
Duplicate of issue #192 , please see 2nd reply on that bug

**Comment by emgucv** [comment] 2021-05-26 19:42
Closing ticket now.

**Closed by emgucv** 2021-05-26 19:42 UTC
