### ISSUE TITLE
Stitch error when image size more than 1MB

### ISSUE THREAD

**Issue by bouyeijiang** [emgucv/emgucv#177] opened 2018-11-15 01:23 UTC
Emgu.CV.Util.CvException:“OpenCV: OpenCL error CL_MEM_OBJECT_ALLOCATION_FAILURE (-4) during call

**Comment by emgucv** [comment] 2018-11-15 02:05
Sounds like Open CV failed to allocating OpenCL memory.

What OpenCL device are you using and what is the amount of memory does the OpenCL device has?

You can disable OpenCL to force the code to run on CPU using computer memory, which, in most of the case should have more memory than your OpenCL device.

**Comment by bouyeijiang** [comment] 2018-11-15 07:48
how to disable OpenCL device, can't to be used GPU?

**Comment by emgucv** [comment] 2018-11-16 15:06
Use Mat instead of UMat and you will be using CPU code path instead of OpenCL code path. You can also set CvInvoke.UseOpenCL to false to force all UMat to follow the CPU code path.

**Comment by bouyeijiang** [comment] 2018-11-22 01:02
how  to do?
the code sample:
public IImage ProcessFunsion(string finder, List<ImageBgrInfo> imgs)
        {
            using (Stitcher stitcher = new Stitcher(false))
            using (FeaturesFinder ff = GetSelectedFeatureFinder(finder))
            using (VectorOfMat vm = new VectorOfMat())
            {
                if (finder != null) stitcher.SetFeaturesFinder(ff);
               
                Mat outMat = new Mat();
                vm.Push(imgs.Select(x => x.ImageBgr).ToArray());

                var status = stitcher.Stitch(vm, outMat);
                if (status == Stitcher.Status.Ok)
                {
                    return outMat;
                }
                else
                {
                    throw new Exception(status.ToString());
                }
            }
        }

**Comment by emgucv** [comment] 2018-11-22 01:07
Run the following code before you ran any other Emgu CV code:

`CvInvoke.UseOpenCL = false;`

**Comment by bouyeijiang** [comment] 2018-11-22 01:54
i want to batch process images ,maybe has 40 pictures,but still throw an exception.
error message:
OpenCV: u != 0

**Comment by emgucv** [comment] 2018-11-22 02:08
Duplicate of #180

**Comment by emgucv** [comment] 2021-07-09 15:16
Closing duplicate ticket now.

**Closed by emgucv** 2021-07-09 15:16 UTC
