### ISSUE TITLE
Can I use this repo to get color quantization.

### ISSUE THREAD

**Issue by zydjohnHotmail** [emgucv/emgucv#711] opened 2022-03-10 21:22 UTC
Hello:
I want to know if I can use this repo to get color quantization for an image.
There are a lot of such repo for Python, as indicated by this web page:
https://github.com/topics/color-quantization
But there no such repo in C#.
Please advise,
Thanks,

**Comment by emgucv** [comment] 2022-03-11 16:59
Not a bug. Closing this ticket, please create a new topic in discussions:
https://github.com/emgucv/emgucv/discussions

**Closed by emgucv** 2022-03-11 16:59 UTC
