### ISSUE TITLE
Can xamarin.forms display video controls?[BUG]

### ISSUE THREAD

**Issue by bbhxwl** [emgucv/emgucv#666] opened 2021-12-04 01:10 UTC
Can xamarin.forms display video controls?

**Comment by emgucv** [comment] 2021-12-21 15:33
Do you means playing a video from a file?

**Comment by bbhxwl** [comment] 2021-12-22 00:40
> Do you means playing a video from a file?

No, I mean, xamarin displays the contents of the camera.

**Comment by emgucv** [comment] 2021-12-29 23:27
Check out the ".zip" release packages, you can download it here:
https://github.com/emgucv/emgucv/releases/tag/4.5.4

Open the visual studio solution under the "Solution" folder. 

In the XamarinForms project, choose "Yolo (DNN model)", the demo allow you to perform realtime object detection using contents from the camera stream.

This ticket is not a BUG, should be a discussion instead.

**Comment by emgucv** [comment] 2022-08-25 23:23
Closing ticket now.

**Closed by emgucv** 2022-08-25 23:23 UTC
