### ISSUE TITLE
Access violation when using Mat.toImage()

### ISSUE THREAD

**Issue by TiredHobgoblin** [emgucv/emgucv#410] opened 2021-02-05 23:15 UTC
I'm using EmguCV to atlas textures from a game. I store a Mat outside of the atlasing loop, and access it as needed. However, it keeps throwing an access violation when I convert the Mat to an Image to add a texture to it. I'm probably going about this the wrong way, so any explanation of how to overlay the textures without converting the Mats to Images would also be appreciated.

The error does not occur every single time the mat is converted to an image, but I've found that it *does* consistently occur at the same point with my testing materials.

Error:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Emgu.CV.CvInvoke.cveMatNumberOfChannels(IntPtr)
   at Emgu.CV.Mat.ToImage[[Emgu.CV.Structure.Bgra, Emgu.CV.Platform.NetStandard, Version=4.5.1.4349, Culture=neutral, PublicKeyToken=7281126722ab4438],[System.Byte, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Boolean)
   at DestinyColladaGenerator.WriteCollada.WriteFile(System.Collections.Generic.List`1<System.Object>, System.String, System.String)
   at DestinyColladaGenerator.Converter.Convert(DestinyColladaGenerator.APIItemData[], System.String, System.String)
   at DestinyColladaGenerator.apiSupport.convertByHash(System.String, System.String[], System.String)
   at DestinyColladaGenerator.apiSupport.convertByHash(System.String, System.String[], System.String)
   at DestinyColladaGenerator.Program.Main(System.String[])
```

Code:
```cs
Dictionary<string, canvasContainer> canvasPlates = new Dictionary<string, canvasContainer>();
Mat ctx;
dynamic plateMetas = renderTextures["texturePlates"];
for (int plateMetaIndex=0; plateMetaIndex<plateMetas.Count; plateMetaIndex++)
{
	dynamic texturePlates = plateMetas[plateMetaIndex];
	if (texturePlates.GetArrayLength() == 1) {
		dynamic texturePlate = texturePlates[0];
		dynamic texturePlateSet = texturePlate.GetProperty("plate_set");

		// Stitch together plate sets
		// Web versions are pre-stitched

		JsonElement.ObjectEnumerator plateProps = texturePlateSet.EnumerateObject();
		while (plateProps.MoveNext())
		{	
			var texturePlateProp = plateProps.Current;
			texturePlate = texturePlateProp.Value;
			string texturePlateId = texturePlateProp.Name;
			string texturePlateRef = texturePlateId+"_"+texturePlate.GetProperty("plate_index");

			string textureId = texturePlateId;
			switch(texturePlateId) {
				case ("diffuse"): textureId = "map"; break;
				case ("normal"): textureId = "normalMap"; break;
				case ("gearstack"): textureId = "gearstackMap"; break;
				case ("dyeslot"): textureId = "dyemap"; break;
				default:
					Console.WriteLine("UnknownTexturePlateId: "+texturePlateId);
					break;
			}

			int canvasWidth = texturePlate.GetProperty("plate_size")[0].GetInt32();
			int canvasHeight = texturePlate.GetProperty("plate_size")[1].GetInt32();
			if (textureId == "dyemap")
			{
				canvasWidth/=4;
				canvasHeight/=4;
			}

			canvasContainer canvasPlate = null;
			if (!canvasPlates.ContainsKey(texturePlateRef)) {
				ctx = new Mat(canvasWidth, canvasHeight, DepthType.Cv8U, 4);

				canvasPlate = new canvasContainer(
					texturePlateId,
					textureId,
					ctx
				);
				canvasPlates.Add(texturePlateRef, canvasPlate);
			}
			else canvasPlate = canvasPlates[texturePlateRef];
			ctx = canvasPlate.image;

			for (int p=0; p<texturePlate.GetProperty("texture_placements").GetArrayLength(); p++) {
				dynamic placement = texturePlate.GetProperty("texture_placements")[p];
				if (!renderTextures.ContainsKey(placement.GetProperty("texture_tag_name").GetString()))
				{
					Console.WriteLine("Missing plate texture detected. Skipping."); continue;
				}
				byte[] placementTexture = renderTextures[placement.GetProperty("texture_tag_name").GetString()];
				Mat imageMat = new Mat();
				CvInvoke.Imdecode(placementTexture, ImreadModes.Unchanged, imageMat);
				Image<Bgra, Byte> imageTex = imageMat.ToImage<Bgra,Byte>();

				if (placementTexture == null) {
					Console.WriteLine("TextureNotLoaded"+placement.texture_tag_name);
					continue;
				}

				Image<Bgra, Byte> ctxImage = ctx.ToImage<Bgra, Byte>(); // ERROR HERE
				ctxImage.ROI = new Rectangle(
					placement.GetProperty("position_x").GetInt32(), 
					placement.GetProperty("position_y").GetInt32(),
					placement.GetProperty("texture_size_x").GetInt32(),
					placement.GetProperty("texture_size_y").GetInt32()
				);
				imageTex.CopyTo(ctxImage);
				ctxImage.ROI = Rectangle.Empty;
				ctx = ctxImage.Mat;
			}
			canvasPlate.image = ctx;
			canvasPlates[texturePlateRef] = canvasPlate;

			Bitmap bm = BitmapExtension.ToBitmap(ctx);
			// save the data to a stream
			bm.Save(Path.Combine(OutLoc, $"{modelName}_{texturePlateRef}.png"), ImageFormat.Png);
		}
	}
	else if (texturePlates.GetArrayLength() > 1) {
		Console.WriteLine("MultipleTexturePlates?");
	}
}
```

**Comment by emgucv** [comment] 2021-02-08 14:13
Will you be able to reproduce the problem with fewer line of code? Preferable in less than 10 lines?

Quite likely the cause of the problem is the Mat got disposed before the Image<,> conversion is completed. If this line is causing the problem:

> Mat imageMat = new Mat();
> CvInvoke.Imdecode(placementTexture, ImreadModes.Unchanged, imageMat);
> Image<Bgra, Byte> imageTex = imageMat.ToImage<Bgra,Byte>();
> 

You can fix it with the C# "using" pattern to make sure the Mat is keep alive during the Image<,> conversion process:

```
Image<Bgra, Byte> imageTex;
using( Mat imageMat = new Mat() )
{ CvInvoke.Imdecode(placementTexture, ImreadModes.Unchanged, imageMat);
  imageTex= imageMat.ToImage<Bgra,Byte>();
}
```
It also help recuded the stress on the garbage collector and keep system memory usage low, because the Mat is disposed right after it is no longer needed.

**Comment by emgucv** [comment] 2021-05-19 20:30
Closing ticket now. 

Please re-open the ticket if you are able to re-produce the issue with a few lines of code.

**Closed by emgucv** 2021-05-19 20:30 UTC
