### ISSUE TITLE
.Net Standard Drawaing / Bitmap compatibility

### ISSUE THREAD

**Issue by WeitesFeld** [emgucv/emgucv#100] opened 2018-02-21 10:56 UTC
Hello,

What are the plans for Drawing / Bitmap functionality for the .net standard build? For some month there is a preview nuget package which include common Drawing components like Bitmap:
https://www.nuget.org/packages/System.Drawing.Common/

**Comment by jackfoxy** [comment] 2019-07-10 17:26
Can the entire library be released in netstandard2.0, or at least net462?
 
net462 is usually (but not guaranteed) compatible with netstandard2.0 builds

**Comment by emgucv** [comment] 2019-07-11 19:04
@WeitesFeld  Have you tried System.Drawing.Common on iOS? I believe System.Drawing.Common depends on native GDI+ library, which do not present in iOS and Android. If introduced as a dependency, as far as I am concerned, it should cause build error in iOS app because iOS app needed to be static linked and native GDI+ is missing. 
For this reason, our .Netstandard prebuild binary do not have a plan to add System.Drawing.Common as dependency yet.

**Comment by emgucv** [comment] 2019-07-11 19:09
@jackfoxy Your request is a duplicate of #1 
The 4.1 release (e.g. libemgucv-windesktop-4.1.0.3420) already includes a file "Emgu.CV.World.Netstandard1_4_.dll" found under the "bin" folder that targets .NetStandard 1.4. Which make it compatible with .NetStandard 2.0 and .Net 4.6.2. 
It is an experimental release and we do not officially support it. Reasons can be found on #1

**Comment by emgucv** [comment] 2021-05-19 20:44
Closing ticket now.

It is part of the Emgu.CV.Bitmap nuget package since in the 4.4.0 release:
https://www.nuget.org/packages/Emgu.CV.Bitmap/

**Closed by emgucv** 2021-05-19 20:44 UTC
