### ISSUE TITLE
Commercial release NuGet package does not provide access to Emgu.CV.UI from .NET Core

### ISSUE THREAD

**Issue by JohnTenney** [emgucv/emgucv#330] opened 2020-05-16 22:25 UTC
Our application has been converted to .NET Core, but we still use classes like BitmapExtension and the ToBitmap functions in the Image class. I believe these are only accessible from Emgu.CV.UI, which is not available to me from the Emgu.CV.runtime.windows-CR.4.2.0.3662 NuGet package from a .NET Core app. I have to separately download and add it as an assembly reference.

**Comment by emgucv** [comment] 2020-05-20 19:29
Duplicate of issue #291 
Bitmap conversion code will included in .NET Core profile in the 4.3 release.

**Comment by emgucv** [comment] 2020-09-14 18:05
Emgu.CV.Bitmap nuget package is available on nuget.org:
https://www.nuget.org/packages/Emgu.CV.Bitmap/

Closing the issue now.

**Closed by emgucv** 2020-09-14 18:05 UTC
