### ISSUE TITLE
No kernel image is available for execution on the device

### ISSUE THREAD

**Issue by HEBOS** [emgucv/emgucv#349] opened 2020-07-18 22:39 UTC
Hi,

I have defined the following function to allow image resize to take place on CUDA.

```
public static Mat Resize(this Mat source, Size size)
        {
            var matDst = new Mat();
            using (GpuMat gMatSrc = new GpuMat())
            using (GpuMat gMatDst = new GpuMat())
            {
                gMatSrc.Upload(source);
                CudaInvoke.Resize(gMatSrc, gMatDst, size);
                gMatDst.Download(matDst);
            }
            return matDst;
        }
```
However, on line **CudaInvoke.Resize(gMatSrc, gMatDst, size)** it raises an exception stating "No kernel image is available for execution on the device".
I have discovered that Maxwell architecture is not supported in your last build, so I created a PR to address that issue.
https://github.com/emgucv/emgucv/pull/350

My environment:
CUDA 10.2
CuDNN 7.6.5
.NET Framework 4.7.2
EmguCV version 4.3.0.3890 (including runtime.windows.cuda)
GPU: GeForce GTX 970M (Maxwell 5.2 capability)

Thanks

**Comment by emgucv** [comment] 2021-02-22 21:33
The 4.3.0 release requires a CUDA device with at least Compute capability of 6.0. 

Maxwell is not supported in Emgu CV 4.3.0

The 4.5.1 release contains compute code that is compatible with Compute capability of 5.2 (Maxwell). Please give the 4.5.1 relase a try. You should also upgrade the NVidia driver to the latest version. 

Seems to be a duplicate of #350 , if all is working please close this ticket. Thanks.

**Comment by emgucv** [comment] 2021-07-08 16:31
Closing ticket now.

**Closed by emgucv** 2021-07-08 16:31 UTC
